### ISSUE TITLE
cache list of valid origins

### ISSUE THREAD

**Issue by hjr3** [hjr3/soldr#1]
See https://github.com/hjr3/soldr/blob/a9686182b1c24394b59aa9db357d31a27dd9dd9e/src/db.rs#L250

We do not want the query the database to get a list of valid origins. Ideally, we have a write through cache so this code is very fast:

https://github.com/hjr3/soldr/blob/a9686182b1c24394b59aa9db357d31a27dd9dd9e/src/proxy.rs#L70-L82

Modifying a list of origins is a rare event relative to reading the list of origins. https://docs.rs/parking_lot/latest/parking_lot/type.RwLock.html might be the best option.

**Comment by QuentinMoss** [comment]
https://github.com/hjr3/soldr/pull/16
