### ISSUE TITLE
Thoughts on semantic release?

### ISSUE THREAD

**Issue by QuentinMoss** [hjr3/soldr#13]
If there's any interest, I've been looking for a reason to set it up and learn the details.

**Comment by hjr3** [comment]
I think you are talking about https://github.com/semantic-release/semantic-release ? This is the first I have heard of it, but this looks like a great idea.

Also, we should generate static binaries for each new release. for example:

- soldr-v1.0.0-x86_64-unknown-linux-musl.tar.gz
- soldr-v1.0.0-aarch64-unknown-linux-musl.tar.gz
   - maybe we don't even need this architecture unless someone asks for it

I don't know if we _need_ the `.tar.gz`, but it seems common when looking at https://github.com/containerd/containerd/releases/tag/v1.7.2

How to generate static binaries: https://stackoverflow.com/a/59766875/775246

**Comment by QuentinMoss** [comment]
Sounds good. I'll create a test branch on my fork before to sort it out and write a README

**Comment by QuentinMoss** [comment]
Do we want to have a release branch that is merged back into `main` or just cut off main?

**Comment by QuentinMoss** [comment]
Closing this for now. The solutions for non-JS projects, specifically Rust, don't seem to be very mature.
