### ISSUE TITLE
Renovate - Automated dependency updates

### ISSUE THREAD

**Issue by QuentinMoss** [hjr3/soldr#21]
Renovate is a service that automates checking for dependency updates and creating pull requests to update dependencies. 

For example: 
If a dependency has a minor patch release we could automate the PR creation and merging if tests pass.
If a dependency has a major change we could require human review / testing prior to releasing.

If you're interested in adding this, I can set up the config - just let me know how you'd like automerging (if any), how often the job runs, etc.

At Honey I configured this to run once a day with a _total_ max number of open PRs set to 5.. reduce dev release/update fatigue.. but I think this project can run often as long as we don't fall behind on tests.

References:
- https://github.com/renovatebot/renovate
- Free hosted instance: https://github.com/marketplace/renovate

**Comment by hjr3** [comment]
This is great stuff. Please set it up. Let us try running it once per week with a total max numbers of open PRs set to 10. We can tweak from there.

**Comment by QuentinMoss** [comment]
@hjr3 Cool, I think you need to install it as an app on this repo. 
https://github.com/marketplace/renovate

If Renovate still works how it used to, it will create a basic config PR after installed. Should be good to merge but we can iterate on it.
