### ISSUE TITLE
Purge requests older than 30 days

### ISSUE THREAD

**Issue by hjr3** [hjr3/soldr#6]
Requests and attempts older than 30 days should be removed from the database.

As part of app startup

https://github.com/hjr3/soldr/blob/a9686182b1c24394b59aa9db357d31a27dd9dd9e/src/main.rs#L62

we probably want to do something like this: https://stackoverflow.com/a/66863562/775246

We can naively check every 30 minutes for now. In the future, we add more configuration.

The `do_something` would be a function call that fetches all `requests` rows in a state of `completed` and delete them. We need to take care to remove these records in such a way that does not cause long-lived locks on the database.

**Comment by QuentinMoss** [comment]
I started working on a solution to this problem, but I'm pretty sure I found a bug with the retry logic. 

I think this may be a valid proposal for avoiding a situation where we get locked into a limit of 10 non-recoverable requests being returned form the DB.

Let me know your thoughts and i'll improve on this and add purge request support

https://github.com/QuentinMoss/soldr/pull/4
