### ISSUE TITLE
Write to sqlite on filesystem

### ISSUE THREAD

**Issue by hjr3** [hjr3/soldr#8]
Per https://github.com/hjr3/soldr/blob/a9686182b1c24394b59aa9db357d31a27dd9dd9e/src/main.rs#L60

we only support in memory database right now.

**Comment by QuentinMoss** [comment]
Hi @hjr3 - I would like to attempt this if its ok. Could you give a little more context/guidance on how to approach this?

**Comment by hjr3** [comment]
I think the first step is introducing some sort of configuration into soldr. This would allow us to specify a database connection string like `sqlite:soldr.db`. I think sane defaults are best, so I imagine something like:

- the default value is `sqlite:soldr.db`
- tests can change the configuration to `sqlite::memory:`
- if a user wants to specify a different location, they can do `sqlite:/path/to/soldr.db`

I would update https://github.com/hjr3/soldr/blob/f54173c7dfbea52756cb0d3d72071bf1a09acddd/src/lib.rs#L26 to accept a `Config` struct. This way a test or `main.rs` can build the config from a file, env vars, etc and pass it in.

```rust
// lib.rs

stuct Config {
   database_url: String,
} 

pub async fn app(config: Config) -> Result<(Router, Router, SqlitePool)> { ... }
```

```rust
// main.rs

#[tokio::main]
async fn main() -> Result<()> {
...

// read config from some config.toml file
let config: Config = ...;

let (ingest, mgmt, pool) = soldr::app(config).await?;

...
```

**Comment by hjr3** [comment]
I landed https://github.com/hjr3/soldr/pull/11 to unlock this. Now, we need to figure out how we init the db.

**Comment by hjr3** [comment]
It looks like `sqlite:soldr.db?mode=rwc` will auto-create the database. See https://github.com/launchbadge/sqlx/issues/1114#issuecomment-827815038
